name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Azure using federated credentials
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Upload to DEV
      - name: Deploy to DEV
        run: |
          az storage blob upload-batch \
            --account-name rushistaticsitesadev \
            -s ./site \
            -d '$web'

      # Upload to STAGE
      - name: Deploy to STAGE
        run: |
          az storage blob upload-batch \
            --account-name rushistaticsitesastage \
            -s ./site \
            -d '$web'

      # Upload to PROD
      - name: Deploy to PROD
        run: |
          az storage blob upload-batch \
            --account-name rushistaticsitesaprod \
            -s ./site \
            -d '$web'
