name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # for OIDC
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://rushistaticsitesadev.z13.web.core.windows.net
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to DEV
        run: |
          az storage blob upload-batch \
            --account-name rushistaticsitesadev \
            -s ./site \
            -d '$web' \
            --auth-mode login \
            --overwrite

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: stage
      url: https://rushistaticsitesastage.z13.web.core.windows.net
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to STAGE
        run: |
          az storage blob upload-batch \
            --account-name rushistaticsitesastage \
            -s ./site \
            -d '$web' \
            --auth-mode login \
            --overwrite

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    environment:
      name: production
      url: https://rushistaticsitesaprod.z13.web.core.windows.net
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to PROD
        run: |
          az storage blob upload-batch \
            --account-name rushistaticsitesaprod \
            -s ./site \
            -d '$web' \
            --auth-mode login \
            --overwrite
