name: Deploy Static Website to Azure
on:
  push:
    branches:
      main

permissions:
  id-token: write
  contents: read

jobs:
  checkout-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    deploy-dev:
      needs: checkout-login
      runs-on: ubuntu-latest

      steps:
      - name: upload to azure static Website dev 
      run: |
        az storage blob upload-batch \
         --account-name ${{ secrets.STORAGE_ACCOUNT_NAME_DEV }} \
         --destination '$web' \
         --source ./site \
         --overwrite 

    deploy-stage:
      needs: deploy-dev
      runs-on: ubuntu-latest

      environment:
        name: stage

      steps:
      - name: upload to azure static Website stage
      run: |
        az storage blob upload-batch \
         --account-name ${{ secrets.STORAGE_ACCOUNT_NAME_STAGE }} \
         --destination '$web' \
         --source ./site \
         --overwrite 

    deploy-prod:
      needs: deploy-stage
      runs-on: ubuntu-latest

      environment:
        name: prod

      steps:
      - name: upload to azure static Website prod
      run: |
        az storage blob upload-batch \
         --account-name ${{ secrets.STORAGE_ACCOUNT_NAME_PROD }} \
         --destination '$web' \
         --source ./site \
         --overwrite 